name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: xcode
      run: |
        $(CC) --version
        sudo xcode-select -switch /Applications/Xcode_12_beta.app
        $(CC) --version
    - name: make
      run: |
        $(CC) --version
        make universal_app
