name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: xcode
      run: sudo xcode-select -s /Applications/Xcode_12_beta.app
    - name: make
      run: make universal_app
